package com.chinasofti.mapper;

import com.chinasofti.pojo.Face;
import com.chinasofti.pojo.FaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    long countByExample(FaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    int deleteByExample(FaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    int insert(Face record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    int insertSelective(Face record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    List<Face> selectByExample(FaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    Face selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Face record, @Param("example") FaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    int updateByExample(@Param("record") Face record, @Param("example") FaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    int updateByPrimaryKeySelective(Face record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    int updateByPrimaryKey(Face record);
}