package com.chinasofti.mapper;

import com.chinasofti.pojo.Ordeing;
import com.chinasofti.pojo.OrdeingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdeingMapper {
	/*添加订单*/
	void inserord(Ordeing ordeing);
	/*显示所有订单*/
	List<Ordeing> showordeing1(int user);
	/*未付钱*/
	List<Ordeing> showordeing2(int user);
	/*付钱未完成*/
	List<Ordeing> showordeing3(int user);
	/*	完成订单*/
	List<Ordeing> showordeing4(int user);
	/*付款成功*/
	void updatState(String ordeid);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    long countByExample(OrdeingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    int deleteByExample(OrdeingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    int insert(Ordeing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    int insertSelective(Ordeing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    List<Ordeing> selectByExample(OrdeingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    Ordeing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Ordeing record, @Param("example") OrdeingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    int updateByExample(@Param("record") Ordeing record, @Param("example") OrdeingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    int updateByPrimaryKeySelective(Ordeing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    int updateByPrimaryKey(Ordeing record);
}