package com.chinasofti.mapper;

import com.chinasofti.pojo.Umessages;
import com.chinasofti.pojo.UmessagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    long countByExample(UmessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    int deleteByExample(UmessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    int insert(Umessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    int insertSelective(Umessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    List<Umessages> selectByExample(UmessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Umessages record, @Param("example") UmessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    int updateByExample(@Param("record") Umessages record, @Param("example") UmessagesExample example);
}