package com.chinasofti.pojo;

import java.util.ArrayList;
import java.util.List;

public class AddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public AddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAddressidIsNull() {
            addCriterion("addressid is null");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNotNull() {
            addCriterion("addressid is not null");
            return (Criteria) this;
        }

        public Criteria andAddressidEqualTo(Integer value) {
            addCriterion("addressid =", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotEqualTo(Integer value) {
            addCriterion("addressid <>", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThan(Integer value) {
            addCriterion("addressid >", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThanOrEqualTo(Integer value) {
            addCriterion("addressid >=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThan(Integer value) {
            addCriterion("addressid <", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThanOrEqualTo(Integer value) {
            addCriterion("addressid <=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidIn(List<Integer> values) {
            addCriterion("addressid in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotIn(List<Integer> values) {
            addCriterion("addressid not in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidBetween(Integer value1, Integer value2) {
            addCriterion("addressid between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotBetween(Integer value1, Integer value2) {
            addCriterion("addressid not between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andProviceIsNull() {
            addCriterion("provice is null");
            return (Criteria) this;
        }

        public Criteria andProviceIsNotNull() {
            addCriterion("provice is not null");
            return (Criteria) this;
        }

        public Criteria andProviceEqualTo(String value) {
            addCriterion("provice =", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceNotEqualTo(String value) {
            addCriterion("provice <>", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceGreaterThan(String value) {
            addCriterion("provice >", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceGreaterThanOrEqualTo(String value) {
            addCriterion("provice >=", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceLessThan(String value) {
            addCriterion("provice <", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceLessThanOrEqualTo(String value) {
            addCriterion("provice <=", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceLike(String value) {
            addCriterion("provice like", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceNotLike(String value) {
            addCriterion("provice not like", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceIn(List<String> values) {
            addCriterion("provice in", values, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceNotIn(List<String> values) {
            addCriterion("provice not in", values, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceBetween(String value1, String value2) {
            addCriterion("provice between", value1, value2, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceNotBetween(String value1, String value2) {
            addCriterion("provice not between", value1, value2, "provice");
            return (Criteria) this;
        }

        public Criteria andAdDetilesIsNull() {
            addCriterion("ad_detiles is null");
            return (Criteria) this;
        }

        public Criteria andAdDetilesIsNotNull() {
            addCriterion("ad_detiles is not null");
            return (Criteria) this;
        }

        public Criteria andAdDetilesEqualTo(String value) {
            addCriterion("ad_detiles =", value, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesNotEqualTo(String value) {
            addCriterion("ad_detiles <>", value, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesGreaterThan(String value) {
            addCriterion("ad_detiles >", value, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesGreaterThanOrEqualTo(String value) {
            addCriterion("ad_detiles >=", value, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesLessThan(String value) {
            addCriterion("ad_detiles <", value, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesLessThanOrEqualTo(String value) {
            addCriterion("ad_detiles <=", value, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesLike(String value) {
            addCriterion("ad_detiles like", value, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesNotLike(String value) {
            addCriterion("ad_detiles not like", value, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesIn(List<String> values) {
            addCriterion("ad_detiles in", values, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesNotIn(List<String> values) {
            addCriterion("ad_detiles not in", values, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesBetween(String value1, String value2) {
            addCriterion("ad_detiles between", value1, value2, "adDetiles");
            return (Criteria) this;
        }

        public Criteria andAdDetilesNotBetween(String value1, String value2) {
            addCriterion("ad_detiles not between", value1, value2, "adDetiles");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 24 12:52:39 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}