package com.chinasofti.pojo;

import java.io.Serializable;

public class Address implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.provice
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String provice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ad_detiles
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String adDetiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressid
     *
     * @return the value of address.addressid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressid
     *
     * @param addressid the value for address.addressid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userid
     *
     * @return the value of address.userid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userid
     *
     * @param userid the value for address.userid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.provice
     *
     * @return the value of address.provice
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getProvice() {
        return provice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.provice
     *
     * @param provice the value for address.provice
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setProvice(String provice) {
        this.provice = provice == null ? null : provice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ad_detiles
     *
     * @return the value of address.ad_detiles
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getAdDetiles() {
        return adDetiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ad_detiles
     *
     * @param adDetiles the value for address.ad_detiles
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setAdDetiles(String adDetiles) {
        this.adDetiles = adDetiles == null ? null : adDetiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", addressid=").append(addressid);
        sb.append(", userid=").append(userid);
        sb.append(", provice=").append(provice);
        sb.append(", adDetiles=").append(adDetiles);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}