package com.chinasofti.pojo;

import java.io.Serializable;

public class Face implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face.id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face.image
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face.group_id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face.user_id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face.id
     *
     * @return the value of face.id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face.id
     *
     * @param id the value for face.id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face.image
     *
     * @return the value of face.image
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face.image
     *
     * @param image the value for face.image
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face.group_id
     *
     * @return the value of face.group_id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face.group_id
     *
     * @param groupId the value for face.group_id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face.user_id
     *
     * @return the value of face.user_id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face.user_id
     *
     * @param userId the value for face.user_id
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face
     *
     * @mbg.generated Thu Sep 26 20:28:44 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", image=").append(image);
        sb.append(", groupId=").append(groupId);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}