package com.chinasofti.pojo;

import java.io.Serializable;

public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brand
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.service_fanwei
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String serviceFanwei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price_stander
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String priceStander;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_img
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.problem
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String problem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.skill
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String skill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsid
     *
     * @return the value of goods.goodsid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsid
     *
     * @param goodsid the value for goods.goodsid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brand
     *
     * @return the value of goods.brand
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brand
     *
     * @param brand the value for goods.brand
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.service_fanwei
     *
     * @return the value of goods.service_fanwei
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getServiceFanwei() {
        return serviceFanwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.service_fanwei
     *
     * @param serviceFanwei the value for goods.service_fanwei
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setServiceFanwei(String serviceFanwei) {
        this.serviceFanwei = serviceFanwei == null ? null : serviceFanwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price_stander
     *
     * @return the value of goods.price_stander
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getPriceStander() {
        return priceStander;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price_stander
     *
     * @param priceStander the value for goods.price_stander
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setPriceStander(String priceStander) {
        this.priceStander = priceStander == null ? null : priceStander.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_img
     *
     * @return the value of goods.goods_img
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_img
     *
     * @param goodsImg the value for goods.goods_img
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.problem
     *
     * @return the value of goods.problem
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.problem
     *
     * @param problem the value for goods.problem
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.skill
     *
     * @return the value of goods.skill
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.skill
     *
     * @param skill the value for goods.skill
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setSkill(String skill) {
        this.skill = skill == null ? null : skill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsid=").append(goodsid);
        sb.append(", name=").append(name);
        sb.append(", brand=").append(brand);
        sb.append(", serviceFanwei=").append(serviceFanwei);
        sb.append(", priceStander=").append(priceStander);
        sb.append(", goodsImg=").append(goodsImg);
        sb.append(", price=").append(price);
        sb.append(", problem=").append(problem);
        sb.append(", skill=").append(skill);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}