package com.chinasofti.pojo;

import java.io.Serializable;
import java.util.Date;

public class Orders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.userid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Integer goodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.service_con
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String serviceCon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.service_time
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Date serviceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.num
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.state
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderid
     *
     * @return the value of orders.orderid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderid
     *
     * @param orderid the value for orders.orderid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.userid
     *
     * @return the value of orders.userid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.userid
     *
     * @param userid the value for orders.userid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodid
     *
     * @return the value of orders.goodid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodid
     *
     * @param goodid the value for orders.goodid
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.service_con
     *
     * @return the value of orders.service_con
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getServiceCon() {
        return serviceCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.service_con
     *
     * @param serviceCon the value for orders.service_con
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setServiceCon(String serviceCon) {
        this.serviceCon = serviceCon == null ? null : serviceCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.service_time
     *
     * @return the value of orders.service_time
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Date getServiceTime() {
        return serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.service_time
     *
     * @param serviceTime the value for orders.service_time
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setServiceTime(Date serviceTime) {
        this.serviceTime = serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.num
     *
     * @return the value of orders.num
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.num
     *
     * @param num the value for orders.num
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.state
     *
     * @return the value of orders.state
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.state
     *
     * @param state the value for orders.state
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", userid=").append(userid);
        sb.append(", goodid=").append(goodid);
        sb.append(", serviceCon=").append(serviceCon);
        sb.append(", serviceTime=").append(serviceTime);
        sb.append(", num=").append(num);
        sb.append(", state=").append(state);
        sb.append(", orderId=").append(orderId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}