package com.chinasofti.pojo;

import java.io.Serializable;
import java.util.Date;

public class Ordeing implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.id
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.user
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private Integer user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.ordeid
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private String ordeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.sumprice
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private String sumprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.servercon
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private String servercon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.servertime
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private Date servertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.brande
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private String brande;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.ordingtime
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private String ordingtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.name
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.tel
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.address
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordeing.state
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.id
     *
     * @return the value of ordeing.id
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.id
     *
     * @param id the value for ordeing.id
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.user
     *
     * @return the value of ordeing.user
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.user
     *
     * @param user the value for ordeing.user
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setUser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.ordeid
     *
     * @return the value of ordeing.ordeid
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public String getOrdeid() {
        return ordeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.ordeid
     *
     * @param ordeid the value for ordeing.ordeid
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setOrdeid(String ordeid) {
        this.ordeid = ordeid == null ? null : ordeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.sumprice
     *
     * @return the value of ordeing.sumprice
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public String getSumprice() {
        return sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.sumprice
     *
     * @param sumprice the value for ordeing.sumprice
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setSumprice(String sumprice) {
        this.sumprice = sumprice == null ? null : sumprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.servercon
     *
     * @return the value of ordeing.servercon
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public String getServercon() {
        return servercon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.servercon
     *
     * @param servercon the value for ordeing.servercon
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setServercon(String servercon) {
        this.servercon = servercon == null ? null : servercon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.servertime
     *
     * @return the value of ordeing.servertime
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public Date getServertime() {
        return servertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.servertime
     *
     * @param servertime the value for ordeing.servertime
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setServertime(Date servertime) {
        this.servertime = servertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.brande
     *
     * @return the value of ordeing.brande
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public String getBrande() {
        return brande;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.brande
     *
     * @param brande the value for ordeing.brande
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setBrande(String brande) {
        this.brande = brande == null ? null : brande.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.ordingtime
     *
     * @return the value of ordeing.ordingtime
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public String getOrdingtime() {
        return ordingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.ordingtime
     *
     * @param ordingtime the value for ordeing.ordingtime
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setOrdingtime(String ordingtime) {
        this.ordingtime = ordingtime == null ? null : ordingtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.name
     *
     * @return the value of ordeing.name
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.name
     *
     * @param name the value for ordeing.name
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.tel
     *
     * @return the value of ordeing.tel
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.tel
     *
     * @param tel the value for ordeing.tel
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.address
     *
     * @return the value of ordeing.address
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.address
     *
     * @param address the value for ordeing.address
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordeing.state
     *
     * @return the value of ordeing.state
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordeing.state
     *
     * @param state the value for ordeing.state
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordeing
     *
     * @mbg.generated Thu Sep 26 12:12:03 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", user=").append(user);
        sb.append(", ordeid=").append(ordeid);
        sb.append(", sumprice=").append(sumprice);
        sb.append(", servercon=").append(servercon);
        sb.append(", servertime=").append(servertime);
        sb.append(", brande=").append(brande);
        sb.append(", ordingtime=").append(ordingtime);
        sb.append(", name=").append(name);
        sb.append(", tel=").append(tel);
        sb.append(", address=").append(address);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}