package com.chinasofti.pojo;

import java.util.ArrayList;
import java.util.List;

public class UmessagesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public UmessagesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andWxidIsNull() {
            addCriterion("wxid is null");
            return (Criteria) this;
        }

        public Criteria andWxidIsNotNull() {
            addCriterion("wxid is not null");
            return (Criteria) this;
        }

        public Criteria andWxidEqualTo(String value) {
            addCriterion("wxid =", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidNotEqualTo(String value) {
            addCriterion("wxid <>", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidGreaterThan(String value) {
            addCriterion("wxid >", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidGreaterThanOrEqualTo(String value) {
            addCriterion("wxid >=", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidLessThan(String value) {
            addCriterion("wxid <", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidLessThanOrEqualTo(String value) {
            addCriterion("wxid <=", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidLike(String value) {
            addCriterion("wxid like", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidNotLike(String value) {
            addCriterion("wxid not like", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidIn(List<String> values) {
            addCriterion("wxid in", values, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidNotIn(List<String> values) {
            addCriterion("wxid not in", values, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidBetween(String value1, String value2) {
            addCriterion("wxid between", value1, value2, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidNotBetween(String value1, String value2) {
            addCriterion("wxid not between", value1, value2, "wxid");
            return (Criteria) this;
        }

        public Criteria andGwIsNull() {
            addCriterion("gw is null");
            return (Criteria) this;
        }

        public Criteria andGwIsNotNull() {
            addCriterion("gw is not null");
            return (Criteria) this;
        }

        public Criteria andGwEqualTo(String value) {
            addCriterion("gw =", value, "gw");
            return (Criteria) this;
        }

        public Criteria andGwNotEqualTo(String value) {
            addCriterion("gw <>", value, "gw");
            return (Criteria) this;
        }

        public Criteria andGwGreaterThan(String value) {
            addCriterion("gw >", value, "gw");
            return (Criteria) this;
        }

        public Criteria andGwGreaterThanOrEqualTo(String value) {
            addCriterion("gw >=", value, "gw");
            return (Criteria) this;
        }

        public Criteria andGwLessThan(String value) {
            addCriterion("gw <", value, "gw");
            return (Criteria) this;
        }

        public Criteria andGwLessThanOrEqualTo(String value) {
            addCriterion("gw <=", value, "gw");
            return (Criteria) this;
        }

        public Criteria andGwLike(String value) {
            addCriterion("gw like", value, "gw");
            return (Criteria) this;
        }

        public Criteria andGwNotLike(String value) {
            addCriterion("gw not like", value, "gw");
            return (Criteria) this;
        }

        public Criteria andGwIn(List<String> values) {
            addCriterion("gw in", values, "gw");
            return (Criteria) this;
        }

        public Criteria andGwNotIn(List<String> values) {
            addCriterion("gw not in", values, "gw");
            return (Criteria) this;
        }

        public Criteria andGwBetween(String value1, String value2) {
            addCriterion("gw between", value1, value2, "gw");
            return (Criteria) this;
        }

        public Criteria andGwNotBetween(String value1, String value2) {
            addCriterion("gw not between", value1, value2, "gw");
            return (Criteria) this;
        }

        public Criteria andKfIsNull() {
            addCriterion("kf is null");
            return (Criteria) this;
        }

        public Criteria andKfIsNotNull() {
            addCriterion("kf is not null");
            return (Criteria) this;
        }

        public Criteria andKfEqualTo(String value) {
            addCriterion("kf =", value, "kf");
            return (Criteria) this;
        }

        public Criteria andKfNotEqualTo(String value) {
            addCriterion("kf <>", value, "kf");
            return (Criteria) this;
        }

        public Criteria andKfGreaterThan(String value) {
            addCriterion("kf >", value, "kf");
            return (Criteria) this;
        }

        public Criteria andKfGreaterThanOrEqualTo(String value) {
            addCriterion("kf >=", value, "kf");
            return (Criteria) this;
        }

        public Criteria andKfLessThan(String value) {
            addCriterion("kf <", value, "kf");
            return (Criteria) this;
        }

        public Criteria andKfLessThanOrEqualTo(String value) {
            addCriterion("kf <=", value, "kf");
            return (Criteria) this;
        }

        public Criteria andKfLike(String value) {
            addCriterion("kf like", value, "kf");
            return (Criteria) this;
        }

        public Criteria andKfNotLike(String value) {
            addCriterion("kf not like", value, "kf");
            return (Criteria) this;
        }

        public Criteria andKfIn(List<String> values) {
            addCriterion("kf in", values, "kf");
            return (Criteria) this;
        }

        public Criteria andKfNotIn(List<String> values) {
            addCriterion("kf not in", values, "kf");
            return (Criteria) this;
        }

        public Criteria andKfBetween(String value1, String value2) {
            addCriterion("kf between", value1, value2, "kf");
            return (Criteria) this;
        }

        public Criteria andKfNotBetween(String value1, String value2) {
            addCriterion("kf not between", value1, value2, "kf");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umessages
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 24 12:52:39 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umessages
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}