package com.chinasofti.pojo;

import java.io.Serializable;

public class UserWithBLOBs extends User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iphone
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String iphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iphone
     *
     * @return the value of user.iphone
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getIphone() {
        return iphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iphone
     *
     * @param iphone the value for user.iphone
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setIphone(String iphone) {
        this.iphone = iphone == null ? null : iphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Sep 24 12:52:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", iphone=").append(iphone);
        sb.append(", email=").append(email);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}